### ISSUE TITLE
希望可以支持指定task目录

### ISSUE THREAD

**Issue by myzhongguo** [odayou/task-processing-extension#1]
我的task都是在看板里管理，daynote用dataview查询展现，也希望可以用dataview查询看板的时间信息统计

**Comment by odayou** [comment]
你好，本插件只适用于我个人的工作场景，即，在一篇笔记里（通常是daily note）记录并统计各事项的时间花费。
只是因为我用obsidian记笔记，所以开发了这个ob的插件，在使用ob之前还做了一个python Gui小工具，但是都是围绕我上面的这个诉求来的，其本质和ob没有任何关系。所以很抱歉不能帮到你，我没精力也没动力添加个人用不到的场景。
其实obsidian本身对于计划的管理挺乏力的，毕竟只是一个md软件，表达能力有限，建议使用专业软件管理计划，比如滴答清单等，我本身试用过kanboard，但是不太灵活，没办法现在正在定制开发一个项目-任务-计划相关的软件，希望能顺利地完成。 祝好

**Comment by odayou** [comment]
你的诉求是要在dataview中统计kanban的数据吗。如果是这样的话最新版的插件可以把耗时写进看板文件的frontmatter中，这样dataview是能统计到的，你可以试试
装了 TimeSaver：看板 .md 跑一次"计算当前笔记"→ frontmatter 写入 time-saver.total_minutes → Dataview 直接查整个看板的总耗时、按标签拆、跨看板汇总，全都能做。
没装 TimeSaver：想统计卡片时间花费，只能自己写 DataviewJS 扫 file.content、用正则解析 10:00 - 11:30、算时长差、聚合——等于把我插件的核心 scanContent + 跨午夜 / by_tag / 中文日期边界（main.ts 的 timePattern、durationMinutes）重写一遍。
